// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ecMsK6hvTvV5Yp13MZmswqmm65n6Ps4',
    appId: '1:1039638710892:web:6f832340efc004a07e2649',
    messagingSenderId: '1039638710892',
    projectId: 'let-s-buy-8700a',
    authDomain: 'let-s-buy-8700a.firebaseapp.com',
    storageBucket: 'let-s-buy-8700a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcDlkUw0cBEAJXTd9gLXkrSrDsbUD1A4k',
    appId: '1:1039638710892:android:80cc5c4b5d338abc7e2649',
    messagingSenderId: '1039638710892',
    projectId: 'let-s-buy-8700a',
    storageBucket: 'let-s-buy-8700a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEl8DhgqFFmvj2thGOrtlrtFBrzslNb20',
    appId: '1:1039638710892:ios:06a2e098cc20261e7e2649',
    messagingSenderId: '1039638710892',
    projectId: 'let-s-buy-8700a',
    storageBucket: 'let-s-buy-8700a.appspot.com',
    iosBundleId: 'com.example.letsBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEl8DhgqFFmvj2thGOrtlrtFBrzslNb20',
    appId: '1:1039638710892:ios:4cb9cba5ffe78aa67e2649',
    messagingSenderId: '1039638710892',
    projectId: 'let-s-buy-8700a',
    storageBucket: 'let-s-buy-8700a.appspot.com',
    iosBundleId: 'com.example.letsBuy.RunnerTests',
  );
}
